### PR TITLE
Updated gamesUtil.js (Closes #34)

### LINKED ISSUE #34: Sorted list of recent games
**Describe the feature you would like**
The list of games in the members area is sorted kind of random due to loading latency.
It would be nice if the newest game would always be at the first position.

There is a pull request fixing this issue.

### PR DESCRIPTION
**Pull request by vincentscode**
Modified so the games will always be sorted correctly.

## Description
There is no need for an async task inside in async task. It destroyes the order of the recent games.

## Related Issue
#34

## Motivation and Context
The change solves the problem of always having to search for recent games in the statistics.

## How Has This Been Tested?
This change has been tested locally with an https-server.

## Screenshots (if appropriate):
Unnecessary.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Scriptim — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
I don't think that this is a good solution at all, because `async: false` is just bad. Rather this sorting should be done in the backend along with returning every game in one request.

**Comment by vincentscode** [comment]
I see no point in just calling something bad for no reason. It works well and is easy to understand. That are the things that count. 
Sorting is done in the backend. The only thing done in the frontend is requesting every game one by one.
If you can come up with a better solution please tell me and i will try to implement it, but this will do the job just fine.

**Comment by ghost** [comment]
Before I continue arguing, please update your branch, because, as you might have seen, the frontend was updated, which means, your branch is not mergeable and the file gamesUtil doesn't even exist anymore.

**Comment by Scriptim** [comment]
"Update" is an unnecessary and very misleading label for a merge conflict imo.

**Pull request closed without merging**
